services:
  devbox:
    build: 
      dockerfile: ./.devcontainer/DockerFile
    container_name: coaster-devbox
    stdin_open: true
    tty: true
    volumes:
      - ./:/workspace/project
    networks:
      - kargo-network
    depends_on:
      - mysql

  mysql:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kargo-network

volumes:
  mysql_data:

networks:
  kargo-network:
    driver: bridge