# Generated by Django 5.2.3 on 2025-06-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("organization_name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=225)),
                ("username", models.CharField(max_length=48)),
                ("password", models.CharField(max_length=255)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.organization",
                    ),
                ),
            ],
        ),
    ]
